# Generated by Django 4.0 on 2023-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pinterest')),
            ],
            options={
                'verbose_name': 'pinterest',
                'verbose_name_plural': 'pinterests',
            },
        ),
    ]
