# Generated by Django 4.2.6 on 2023-10-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0004_alter_pinterest_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinterest',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
